name: InvisiNOT
main: net.drgnome.invisinot.InvisiPlugin
version: 1.0.1
author: Siguza
depend: [ProtocolLib]
permissions:
  invisinot.see:
    default: op
    description: "Allows you to see invisible players"
  invisinot.update:
    default: op
    description: "Notifies you of new InvisiNOT versions"